### PR TITLE
fix couple typos and improve consistency in CSS (fixes #16)

### LINKED ISSUE #16: Fix up a few typos in CSS

### PR DESCRIPTION
**Pull request by cvan**

### CODE REVIEW

**Comment by mattbasta** [comment]
Lgtm. Has merge conflicts tho

**Comment by cvan** [comment]
I just pulled, rebased, and no conflicts. force pushed, and I still see this conflict message on GitHub. wth?

**Comment by mattbasta** [comment]
You didn't rebase against the real master, you rebased against your own master

**Comment by mattbasta** [comment]
C'mon @cvan, haven't you mastered git?

**Pull request closed without merging**
